### ISSUE TITLE
avail-light Crash Report

### ISSUE THREAD

**Issue by GabrielFMontoni** [availproject/avail-light#384]
I didn't found Avail's email then i decided to post here the issue.

Panic occurred in file '/home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-swarm-0.44.0/src/handler/either.rs' at line 106
"""
"cause" = "internal error: entered unreachable code"
"method" = "Panic"
"backtrace" = """

   0: 0x559f2f23fcf3 - <unresolved>
   1: 0x559f2f3c4502 - <unresolved>
   2: 0x559f2f480881 - <unresolved>
   3: 0x559f2fbf7783 - <unresolved>"""

Well, this is embarrassing.

avail-light had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "<Failed to store file to disk>". Submit an issue or email with the subject of "avail-light Crash Report" and include the report as an attachment.

- Authors: Avail Team

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
2023-12-13T12:02:42.376646Z ERROR avail_light: Error: The application panicked (crashed).
Message:  internal error: entered unreachable code
Location: 

This is bug. Please, consider reporting it to us at https://github.com/availproject/avail-light.git

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by sh3ll3x3c** [comment]
Thanks for the report @GabrielFMontoni!

This issue has been resolved in one of the previous releases that contained a `libp2p` update.
