### ISSUE TITLE
avail-light Crash Report

### ISSUE THREAD

**Issue by Madmin27** [availproject/avail-light#393]
Hi, When I look at it after a while, it is closed. I'm getting this warning
v1.7.5-rc4
Ubuntu 22.04

---
Well, this is embarrassing.

avail-light had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-abff24d3-44e6-4a27-b8e6-316225408df8.toml". Submit an issue or email with the subject of "avail-light Crash Report" and include the report as an attachment.

- Authors: Avail Team

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
2023-12-21T23:19:34.130469Z ERROR avail_light: Error: The application panicked (crashed).
Message:  RPC Subscription stream should be infinite
Location: /home/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs:217

This is bug. Please, consider reporting it to us at https://github.com/availproject/avail-light.git

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets. 
![Ekran görüntüsü 2023-12-22 093435](https://github.com/availproject/avail-light/assets/94014225/0a3ee322-1be3-444a-a17e-da78b91ce563)

**Comment by Madmin27** [comment]
RUST_BACKTRACE=full
./avail-light --network goldberg

![Ekran görüntüsü 2023-12-22 094220](https://github.com/availproject/avail-light/assets/94014225/240397a6-049c-4f25-8c5c-b25d1c8d93c6)

**Comment by sh3ll3x3c** [comment]
Thanks for the report @Madmin27!

We are currently working on a new version of the light client that will include fixes for the issues you’ve been experiencing which will include a new, configurable, RPC call retry mechanism. We are currently testing this and will be releasing the new version of the Light client soon, so please stay tuned for further announcements and releases.
