### ISSUE TITLE
Error: The application panicked (crashed) - Light Node Error

### ISSUE THREAD

**Issue by Cordeiro71** [availproject/avail-light#402]
Message:  RPC Subscription stream should be infinite
Location: /root/avail-light/src/network/rpc/event_loop.rs:221

**Comment by sh3ll3x3c** [comment]
Thanks for the report @Cordeiro71!

We are currently working on a new version of the light client that will include fixes for the issues you’ve been experiencing which will include a new, configurable, RPC call retry mechanism. We are currently testing this and will be releasing the new version of the Light client soon, so please stay tuned for further announcements and releases.
