### ISSUE TITLE
Avail-Light Crash report - version 1.7.5 RC5

### ISSUE THREAD

**Issue by Bosshsieh000** [availproject/avail-light#404]
When attempting to run a node, I encountered the following error:

The program crashed. The error message indicates "RPC Subscription stream should be infinite," located at D:\avail-light\src\network\rpc\event_loop.rs, line 221. This is considered a bug. It is recommended to run the program with the environment variable RUST_BACKTRACE=1 or RUST_BACKTRACE=full set to display a more detailed backtrace. 

Crash info as follow:
`The application panicked (crashed).
Message:  RPC Subscription stream should be infinite
Location: D:\avail-light\src\network\rpc\event_loop.rs:221

This is bug. Please, consider reporting it to us at https://github.com/availproject/avail-light.git

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Well, this is embarrassing.

avail-light had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "C:\Temp\BOSSHS~1\report-d0ea8185-a018-408b-a8b5-4ef22e3d26d5.toml". Submit an issue or email with the subject of "avail-light Crash Report" and include the report as an attachment.

- Authors: Avail Team

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
2024-01-06T09:20:57.659475Z ERROR avail_light: Error: The application panicked (crashed).
Message:  RPC Subscription stream should be infinite
Location: D:\avail-light\src\network\rpc\event_loop.rs:221

This is bug.`

**Comment by sh3ll3x3c** [comment]
Thanks for the report @Bosshsieh000!

We are currently working on a new version of the light client that will include fixes for the issues you’ve been experiencing which will include a new, configurable, RPC call retry mechanism. We are currently testing this and will be releasing the new version of the Light client soon, so please stay tuned for further announcements and releases.
