### ISSUE TITLE
avail-light Crash Report 1.7.4

### ISSUE THREAD

**Issue by script-money** [availproject/avail-light#405]
"name" = "avail-light"
"operating_system" = "Mac OS 14.2.1 [64-bit]"
"crate_version" = "1.7.4"
"explanation" = """
Panic occurred in file '/Users/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs' at line 221
"""
"cause" = "RPC Subscription stream should be infinite"
"method" = "Panic"
"backtrace" = """

   0: 0x10345d33a - core::option::expect_failed::h7a284305b411661c
   1: 0x1023af961 - avail_light::network::rpc::event_loop::EventLoop::run::{{closure}}::ha8c3e925446965df
   2: 0x10234adb5 - <avail_light::shutdown::with_cancel::WithCancel<T,F> as core::future::future::Future>::poll::he9693eee5c7beed4
   3: 0x1024a485c - tokio::runtime::task::raw::poll::hcd8925c5b5fa4e2f
   4: 0x102db1a6d - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hdb1283b117571b63
   5: 0x102db5c1e - tokio::runtime::task::raw::poll::hc841fc0736276968
   6: 0x102da735c - std::sys_common::backtrace::__rust_begin_short_backtrace::hedcc2edb69b5d537
   7: 0x102da711c - core::ops::function::FnOnce::call_once{{vtable.shim}}::he1cf7c74741df83e
   8: 0x102d71629 - std::sys::unix::thread::Thread::new::thread_start::h38ac7fbd1086ae35
   9: 0x7ff80aa27202 - __pthread_start"""

**Comment by sh3ll3x3c** [comment]
Thanks for the report @script-money!

We are currently working on a new version of the light client that will include fixes for the issues you’ve been experiencing which will include a new, configurable, RPC call retry mechanism. We are currently testing this and will be releasing the new version of the Light client soon, so please stay tuned for further announcements and releases.
