### ISSUE TITLE
avail-light Crash Report v1.7.5-rc5

### ISSUE THREAD

**Issue by trevorfs** [availproject/avail-light#406]
This is bug. Please, consider reporting it to us at https://github.com/availproject/avail-light.git

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Well, this is embarrassing.

avail-light had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-e8ad329e-ae89-433f-a04c-c51a3d74b836.toml". Submit an issue or email with the subject of "avail-light Crash Report" and include the report as an attachment.

- Authors: Avail Team

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
2024-01-08T21:00:37.039522Z ERROR avail_light: Error: The application panicked (crashed).
Message:  RPC Subscription stream should be infinite
Location: /home/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs:221

This is bug. Please, consider reporting it to us at https://github.com/availproject/avail-light.git

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

ERROR ALERT

"name" = "avail-light"
"operating_system" = "Ubuntu 22.04 (jammy) [64-bit]"
"crate_version" = "1.7.4"
"explanation" = """
Panic occurred in file '/home/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs' at line 221
"""
"cause" = "RPC Subscription stream should be infinite"
"method" = "Panic"
"backtrace" = """

   0: 0x7f351273dff5 - <avail_light::shutdown::with_cancel::WithCancel<T,F> as core::future::future::Future>::poll::h19a746bdf2964f33
   1: 0x7f35128958d0 - tokio::runtime::task::raw::poll::h0ec5c28c88525fee
   2: 0x7f35131dd30f - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hc4ba8750e7a4dfc0
   3: 0x7f35131e07ae - tokio::runtime::task::raw::poll::h3c65b87534e87ff4
   4: 0x7f35131d40d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf83e749dafb7aac7
   5: 0x7f35131d3ec2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3a7db27698b3c2be
   6: 0x7f351319f035 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h51435299acd7166e
                at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007
                 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3f833c0a4926bdd4
                at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007
                 - std::sys::unix::thread::Thread::new::thread_start::h2c486d0230ab0d99
                at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108
   7: 0x7f3511fe4ac3 - <unresolved>
   8: 0x7f3512075814 - __clone
   9:        0x0 - <unresolved>"""

**Comment by trevorfs** [comment]
I followed the instructions for running a light client with default config on the goldberg network found here:

https://docs.availproject.org/operate/node/light-client/

The client seems processing everything normally until it crashed with the following error:
![image](https://github.com/availproject/avail-light/assets/36541416/df4ff439-769f-4106-a585-2864eb5402ef)
i tried to running again and waiting if still get bug or not thanks

**Comment by sh3ll3x3c** [comment]
Thanks for the report @trevorfs!

We are currently working on a new version of the light client that will include fixes for the issues you’ve been experiencing which will include a new, configurable, RPC call retry mechanism. We are currently testing this and will be releasing the new version of the Light client soon, so please stay tuned for further announcements and releases.
