### ISSUE TITLE
avail-light Crash Report 1.7.4

### ISSUE THREAD

**Issue by jnixable** [availproject/avail-light#410]
"name" = "avail-light"
"operating_system" = "Mac OS 14.2.1 [64-bit]"
"crate_version" = "1.7.4"
"explanation" = """
Panic occurred in file '/Users/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs' at line 221
"""
"cause" = "RPC Subscription stream should be infinite"
"method" = "Panic"
"backtrace" = """

0: 0x105b8333a - core::option::expect_failed::h7a284305b411661c
1: 0x104ad5961 - avail_light::network::rpc::event_loop::EventLoop::run::{{closure}}::ha8c3e925446965df
2: 0x104a70db5 - <avail_light::shutdown::with_cancel::WithCancel<T,F> as core::future::future::Future>::poll::he9693eee5c7beed4
3: 0x104bca85c - tokio::runtime::task::raw::poll::hcd8925c5b5fa4e2f
4: 0x1054d7a6d - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hdb1283b117571b63
5: 0x1054dbc1e - tokio::runtime::task::raw::poll::hc841fc0736276968
6: 0x1054cd35c - std::sys_common::backtrace::__rust_begin_short_backtrace::hedcc2edb69b5d537
7: 0x1054cd11c - core::ops::function::FnOnce::call_once{{vtable.shim}}::he1cf7c74741df83e
8: 0x105497629 - std::sys::unix::thread::Thread::new::thread_start::h38ac7fbd1086ae35
9: 0x7ff81b65f202 - __pthread_start"""

**Comment by sh3ll3x3c** [comment]
Thanks for the report @jnixable!

We've reproduced this issue, and the main cause are the intermittent RPC drops between the LC and the node. 

We are currently working on a new version of the light client that will include fixes for the issues you’ve been experiencing which will include a new, configurable, RPC call retry mechanism. We are currently testing this and will be releasing the new version of the Light client soon, so please stay tuned for further announcements and releases.
