### ISSUE TITLE
avail-light Crash Report 1.7.4

### ISSUE THREAD

**Issue by jnixable** [availproject/avail-light#411]
2024-01-10T13:15:08.397100Z  INFO avail_light::light_client: Confidence factor: 99.90234375 block_number=272918 confidence=99.90234375
2024-01-10T13:15:08.397936Z  INFO avail_light::api::v2: Message published to clients topic=ConfidenceAchieved published=0 failed=0
2024-01-10T13:15:08.399259Z  INFO avail_light::network::p2p::event_loop: Cell upload success rate for block 272918: 0/10. Duration: 0
2024-01-10T13:15:26.204037Z  INFO avail_light::network::rpc::event_loop: Header no.: 272919
2024-01-10T13:15:26.204931Z  INFO avail_light::network::rpc::event_loop: New justification at block no.: 272919, hash: 0x3a9b3188a70df6820c4cbf70ea5517cddfe95256e713befd0eae92aca0ed9ec5
Panic shutdown triggered with success, awaiting completion...
2024-01-10T13:15:26.218974Z  INFO avail_light::network::p2p::event_loop: Shuting down P2P Event Loop. Please wait...
2024-01-10T13:15:26.219093Z  INFO avail_light::network::p2p::event_loop: P2P Event Loop shutdown complete.
Shutdown completed.
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: 
   0: Not signed by this signature! Sig id: 049dc4d5d57dcafbf3d773f4894fb50b5c1071cf0732ddd0e185afcd894382fa (5CAkv5Af...), set_id: 125, justification: GrandpaJustification { round: 44514, commit: Commit { target_hash: 0x3a9b3188a70df6820c4cbf70ea5517cddfe95256e713befd0eae92aca0ed9ec5, target_number: 272919, precommits: [SignedPrecommit { precommit: Precommit { target_hash: 0x3a9b3188a70df6820c4cbf70ea5517cddfe95256e713befd0eae92aca0ed9ec5, target_number: 272919 }, signature: 83e2a7396ba82716d472bdcc1f6d63e1ae2c22e4be513d9e1ebe297eefbcf7b5e512fcfe1c77106b440e4ca84e471b537d410f6bd5a7f1ff753abaabd7a2e703, id: 0233b669b30fa8fdbaa159dca673cdc3ca7afc1284e3a9e49023c521c634217d (5C7bKD8H...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: eaed45538f85b6bc510ef0d47e26ca47f0b8725e4f1c28e2f2480437aba8912693400037cc812efc0fada3baee8a32af42a48ea00de761fe4d488714750ef801, id: 049dc4d5d57dcafbf3d773f4894fb50b5c1071cf0732ddd0e185afcd894382fa (5CAkv5Af...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: 4e9e0cb03caffa1ed7aa3551e47afbe140d10e151dab05987c446b35f40165ad0eaa3a7fb19350841e5d99e6e90f54f18abb88d9b5fd8a77e6411101f9c13a09, id: 04b453a0c525b6b1fc79343f3d7c846da173d5082b09cb0b46433a9a7f2190ce (5CAscjYC...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: 241157f2afd789e9deb423b01a221fee0d322a947967df6a83fe760ca0d7990da6ed2ba2fb22a97c4aa69134d08ef3a0cdce62ab4829402d4e3ba2cbb5f5eb08, id: 05bf2ef8c14b9f403575cc8767e039996c23196358e310076f2fe9f3774be033 (5CCEta1t...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: 1348331c4d5079a83955cb9eb1298433f01dfef321daa84441f9187e4d09fbf4cae7bea67cb3244176cb25e7151185f568d449a47c3f7b376a3d55d618a88d0f, id: 069cae25d264b387be3145f1eea2f37eb189a99d192bc2bfcdf2ada2ee5e38b6 (5CDNgsTR...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: 7868bc8ffc3e8fccbaaca9e6053c532abe4ba739183a23cbda838236432031ce4279d925644e5c629c982ace0fa1edcd4215d5023fe172e9db705548d55caf09, id: 07d1d3c727a805d96101d40951a15e16dda04b79281e2e44e03619c791f6f887 (5CExXMDi...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: a0780d0e6c7a1225c3a042df404b9c2aed81d3656a4fa0dedd0e99e38129ce3ea6451594081ed6d7b9ece6738165fa48196f5fd6ae4466fbed6e16d0a7461f06, id: 0c5be9f12e20b312f83cd8caa54fa2373799880843a884332e4f1032c9d18eba (5CLujdnX...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: 404b0e569c107916596cad5f1f5783fc330413a020cc9c1af3c0561f8e7c943d8d5f9a0fcb04ae2486d543cd0659fd97bcbdce5334b524ef1e6615da6ebe2e06, id: 0ce92d5891230a7f43621a795256d0fdd4a376564667a51ce392af49fd2b7c3a (5CMdhYZX...) }, SignedPrecommit { precommit: Precommit { target_hash: 0x3a9b3188a70df6820c4cbf70ea5517cddfe95256e713befd0eae92aca0ed9ec5, target_number: 272919 }, signature: cc33bec446556cadfc4e14ee5d71573cd8488b87fe1d6803903d9ecb65766b96650491f8b714b8da9ae9af0bdacee91d3f0a4815289f9c4a1cd7f295c7ad6a0c, id: 0cf7166edaa8a7b58d9f4d143bb71ec721ac65cbae7a1e2337e33a91fa2b296b (5CMhqDZ4...) }, SignedPrecommit { precommit: Precommit { target_hash: 0xbb218fb885497d899f8689a76c50d7b7bdde4f8e3135feb972899dbb24d1e8e3, target_number: 272920 }, signature: 170ebcde9d2361c7d30cc8fcc593bd29f8e5eef674aae7f13109baa09e4f1544b33c58e5ff2271bba99ee89cff5628273400652b7846d25f7a5d433cc399910a, id: 0e6645b6f2018e722bb3b05693bb3b722dfc5c096ee07c98ae474c1698f9cf6b (5CPaufMz...) }, 

....

Location:
   /Users/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs:322

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Location: /Users/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs:332

This is bug. Please, consider reporting it to us at https://github.com/availproject/avail-light.git

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.

Location:
   \u001B[35m/Users/runner/work/avail-light/avail-light/src/network/rpc/event_loop.rs\u001B[0m:\u001B[35m322\u001B[0m

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets."""
"method" = "Panic"
"backtrace" = """

   0: 0x105ba32d5 - core::result::unwrap_failed::h1dfc845201666161
   1: 0x104aeea58 - avail_light::network::rpc::event_loop::EventLoop::handle_subscription_stream::{{closure}}::hef4e7cb7bb7627f4
   2: 0x104af5622 - avail_light::network::rpc::event_loop::EventLoop::run::{{closure}}::ha8c3e925446965df
   3: 0x104a90db5 - <avail_light::shutdown::with_cancel::WithCancel<T,F> as core::future::future::Future>::poll::he9693eee5c7beed4
   4: 0x104bea85c - tokio::runtime::task::raw::poll::hcd8925c5b5fa4e2f
   5: 0x1054f7a6d - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hdb1283b117571b63
   6: 0x1054fbc1e - tokio::runtime::task::raw::poll::hc841fc0736276968
   7: 0x1054ed35c - std::sys_common::backtrace::__rust_begin_short_backtrace::hedcc2edb69b5d537
   8: 0x1054ed11c - core::ops::function::FnOnce::call_once{{vtable.shim}}::he1cf7c74741df83e
   9: 0x1054b7629 - std::sys::unix::thread::Thread::new::thread_start::h38ac7fbd1086ae35
  10: 0x7ff81b65f202 - __pthread_start"""

**Comment by sh3ll3x3c** [comment]
Hey @jnixable, thanks for reporting!

This was a justification bug that was resolved in the [1.7.6](https://github.com/availproject/avail-light/releases/tag/v1.7.6) version. If you run across it again, please feel free to report/reopen the issue!
