### ISSUE TITLE
Avail Light Crashing Latest  v1.7.5 RC9

### ISSUE THREAD

**Issue by goonerholic-crypto** [availproject/avail-light#424]
024-01-25T08:19:30.092416Z ERROR avail_light::light_client: Cannot process block: Rpc error: RPC error: RPC call failed: ErrorObject { code: ServerError(-32001), message: "Custom error: failed to construct block: Custom error: Block Length cannot be fetched: Application(Execution(RuntimeConstruction(Other(\"failed to instantiate a new WASM module instance: maximum concurrent instance limit of 32 reached\"))))", data: None }
2024-01-25T08:19:30.096422Z  INFO avail_light::network::p2p::event_loop: Shuting down P2P Event Loop. Please wait...
2024-01-25T08:19:30.096701Z  INFO avail_light::network::p2p::event_loop: P2P Event Loop shutdown complete.
2024-01-25T08:19:30.096766Z ERROR avail_light::sync_finality: Cannot sync finality Couldn't get header for 0x11ff…d551
Error:
   0: Running Light Client encountered an error
   1: Cannot process block: Rpc error: RPC error: RPC call failed: ErrorObject { code: ServerError(-32001), message: "Custom error: failed to construct block: Custom error: Block Length cannot be fetched: Application(Execution(RuntimeConstruction(Other(\"failed to instantiate a new WASM module instance: maximum concurrent instance limit of 32 reached\"))))", data: None }: RPC error: RPC call failed: ErrorObject { code: ServerError(-32001), message: "Custom error: failed to construct block: Custom error: Block Length cannot be fetched: Application(Execution(RuntimeConstruction(Other(\"failed to instantiate a new WASM module instance: maximum concurrent instance limit of 32 reached\"))))", data: None }

Location:
   src/bin/avail-light.rs:502

**Comment by sh3ll3x3c** [comment]
Hey @goonerholic-crypto , thanks for reporting this!

A temporary issue arose on the node side, that was fixed since. You shouldn't see these errors occurring anymore, but if you do - please feel free to reopen the issue.
