### ISSUE TITLE
wallet adress

### ISSUE THREAD

**Issue by trankil123** [availproject/avail-light#455]
hi
i have put my seed phrase in identity.toml 

`avail_secret_seed_phrase = "myseeed phrase//Alice"`

i have nano my .service like this 
 `[Unit]
Description=Avail Light Client
After=network.target
StartLimitIntervalSec=0
[Service]
User=root
ExecStart= /home/trankil/avail-light/target/release/avail-light --identity '~/avail-light/target/release/identity.toml' --network goldberg
Restart=always
RestartSec=120
[Install]
WantedBy=multi-user.target`

reload daemon restart service and when i ` systemctl status availd.service`

i have always an other wallet adress display here
`févr. 19 20:21:41 vm avail-light[127258]: 2024-02-19T20:21:41.034680Z  INFO avail_light: Avail address is: 5GHDUC4QiQb8baMrrEMBRDDvQxwitVcd6qxYEdaRoFt1nNNP`

thanks

**Comment by manhlinhng** [comment]
Save addr: `5GHDUC4QiQb8baMrrEMBRDDvQxwitVcd6qxYEdaRoFt1nNNP `and your seed.

**Comment by aterentic-ethernal** [comment]
Hello @trankil123 , can you try to put absolute path instead of `~/avail-light/target/release/identity.toml`, since service is run by root user? Thanks

**Comment by trankil123** [comment]
thx its work !
