### ISSUE TITLE
Both seed phrase but not same address

### ISSUE THREAD

**Issue by vinatechpro** [availproject/avail-light#462]
Why address when check status Avail Light Client different with address import to Subwallet. Both same seed phrase. What wallet i need use for same address?

![IMG_20240224_171912_743.jpg](https://github.com/availproject/avail-light/assets/149946061/abb7bfe0-58e9-4931-8283-3a90c5e55da3)

![IMG_20240224_171917_066.jpg](https://github.com/availproject/avail-light/assets/149946061/437b5867-1ff4-4824-9442-d66681b42079)

**Comment by manhlinhng** [comment]
Have you tried import the seed phrase to pokadot.js ext wallet?

**Comment by manhlinhng** [comment]
> > Have you tried import the seed phrase to pokadot.js ext wallet?
> 
> I tried import to Subwallet and Pokadot.js wallet. Both have the same seed and address. But the LC export status wallet address is different. Please check me Exec service file.
> 
> ```
> [Unit]
> Description=Avail Light Client
> After=network.target
> StartLimitIntervalSec=0
> [Service]
> User=root
> ExecStart= /root/avail-light/target/release/avail-light --identity '~/avail-light/target/release/identity.toml' --network goldberg
> Restart=always
> RestartSec=120
> [Install]
> WantedBy=multi-user.target
> ```
> 
> ```
> nano ~/avail-light/target/release/identity.toml
> ```
> 
> Format identity file (seed demo)
> 
> ```
> # identity.toml
> avail_secret_seed_phrase = "bottom drive obey lake curtain smoke basket hold race lonely fit walk"
> ```

Chang your path: 
`~/avail-light/target/release/identity.toml`
To:
`'/root/avail-light/target/release/identity.toml'`

**Comment by vinatechpro** [comment]
> > > Have you tried import the seed phrase to pokadot.js ext wallet?
> > 
> > 
> > I tried import to Subwallet and Pokadot.js wallet. Both have the same seed and address. But the LC export status wallet address is different. Please check me Exec service file.
> > ```
> > [Unit]
> > Description=Avail Light Client
> > After=network.target
> > StartLimitIntervalSec=0
> > [Service]
> > User=root
> > ExecStart= /root/avail-light/target/release/avail-light --identity '~/avail-light/target/release/identity.toml' --network goldberg
> > Restart=always
> > RestartSec=120
> > [Install]
> > WantedBy=multi-user.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > nano ~/avail-light/target/release/identity.toml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Format identity file (seed demo)
> > ```
> > # identity.toml
> > avail_secret_seed_phrase = "bottom drive obey lake curtain smoke basket hold race lonely fit walk"
> > ```
> 
> Chang your path: `~/avail-light/target/release/identity.toml` To: `/root/avail-light/target/release/identity.toml`

Thank bro, It working!
