### ISSUE TITLE
AVAIL Discord 

### ISSUE THREAD

**Issue by benoit80000** [availproject/avail-light#484]
Hello since several month i can't enter in avail discord, i can deploy a node cause i can't claim faucet.
It'is not fair, can't have support.
https://lightclient.availproject.org/

**Comment by kri8423** [comment]
![Screenshot 2024-04-04 165403](https://github.com/availproject/avail-light/assets/166015907/85c509b8-fe0e-4964-bdd1-145ca365a1c1)
![Screenshot 2024-04-04 165403](https://github.com/availproject/avail-light/assets/166015907/77057e31-74b6-44e6-b2e9-756162e21dad)

**Comment by kri8423** [comment]
pleasae solution

**Comment by adpadam602** [comment]
curl -sL1 avail.sh | bash

**Comment by Ashishbhai123** [comment]
What is the solution for error

**Comment by robin-rrt** [comment]
Please [look here](https://forum.availproject.org/t/avails-light-client-lift-off-challenge-status/1225) for light client challenge status.  

If you face any issues please report on [Discord](https://discord.gg/y6fHnxZQX8).

[Report here](https://forum.availproject.org/t/use-this-thread-discord-issues-thread/897) if you're facing issues in joining Discord.
