### ISSUE TITLE
mac m1 can not run avail-light-apple-arm64 

### ISSUE THREAD

**Issue by hrsdef** [availproject/avail-light#487]
<img width="563" alt="WechatIMG18498" src="https://github.com/availproject/avail-light/assets/51474734/8cdd0cfa-d25c-4274-bb6b-352f5743bb27">

**Comment by prabal-banerjee** [comment]
Please use Availup. https://docs.availproject.org/docs/operate-a-node/run-a-light-client/0010-light-client#running-the-light-client-linux-macos
