### ISSUE TITLE
Testnet explorer not working 

### ISSUE THREAD

**Issue by wnhedaxx** [availproject/avail-light#488]
https://avail-testnet.subscan.io/extrinsic/0xea7799349306db98e37700e05b30551d54e16dcc6fc22112e8cbdff2be59845f

i have minted Blobscriptions nft from https://lightclient.availproject.org/ ..... but when i see on explorer "The extrinsic related to 0xea7799349306db98e37700e05b30551d54e16dcc6fc22112e8cbdff2be59845f is not found"
![image](https://github.com/availproject/avail-light/assets/70830772/6e48f8ec-4e42-4f6e-b35e-644d1f19a449)

**Comment by prabal-banerjee** [comment]
Should work now. Thanks.
