### ISSUE TITLE
Failed to connect any appropriate working node

### ISSUE THREAD

**Issue by ciskhalifa** [availproject/avail-light#489]
![error](https://github.com/availproject/avail-light/assets/23627467/28af3f57-22a4-4381-a091-f5d641f7916d)

in my windows error like that, how to re run ?

**Comment by git-clone-abhinav** [comment]
same here

**Comment by praveenyadav1602** [comment]
same error,

**Comment by prabal-banerjee** [comment]
Retrying should work. Otherwise, Discord/TG would be the right forum to discuss this.
