### ISSUE TITLE
node run problem

### ISSUE THREAD

**Issue by Sudipta199** [availproject/avail-light#501]
![Screenshot 2024-04-06 141637](https://github.com/availproject/avail-light/assets/91684883/a9535fba-46f4-4a97-9cda-50e214141fb9)
please solve my problem
![Screenshot 2024-04-06 141649](https://github.com/availproject/avail-light/assets/91684883/70c58c3e-9057-41a0-8e5d-0d8dcb8d5561)

**Comment by prabal-banerjee** [comment]
Unrelated to the project
