### ISSUE TITLE
NODE ISSUE

### ISSUE THREAD

**Issue by ELiTE0005** [availproject/avail-light#502]
curl -sL1 http://avail.sh | bash

node always not working !

**Comment by dinodinoy** [comment]
curl -sL1 http://avail.sh/ | bash NOT WORKING

**Comment by saurabhkumar90** [comment]
yes not working

**Comment by mastershav93** [comment]
curl -sL1 avail.sh | bash

**Comment by prabal-banerjee** [comment]
Let's discuss the issues on Discord/TG. Retrying should work in general.
