### ISSUE TITLE
Setting config.yml in version 1.8.0  is not working

### ISSUE THREAD

**Issue by ianhomew** [availproject/avail-light#519]
Hi devs,

`avail-light --config /root/avail-light/config.yml --network goldberg --identity /root/avail-light/identity.toml`

My problem is that the config file is not working. avail-light still load the old default config in v1.8.0

Here is the config.yml below which is from "avail.sh":

```
bootstraps=['/dns/bootnode.2.lightclient.goldberg.avail.tools/tcp/37000/p2p/12D3KooWRCgfvaLSnQfkwGehrhSNpY7i5RenWKL2ARst6ZqgdZZd','/dns/bootnode.1.lightclient.goldberg.avail.tools/tcp/37000/p2p/12D3KooWBkLsNGaD3SpMaRWtAmWVuiZg1afdNSPbtJ8M8r9ArGRT']
full_node_ws=['wss://rpc-testnet.avail.tools/ws','wss://avail-goldberg-rpc.lgns.xyz:443/ws','wss://rpc-goldberg.sandbox.avail.tools:443','wss://avail-goldberg.public.blastapi.io:443','wss://lc-rpc-goldberg.avail.tools:443/ws']
confidence=80.0
avail_path='/root/avail-light/avail_path'
kad_record_ttl=43200
ot_collector_endpoint='http://otelcol.lightclient.goldberg.avail.tools:4317'
genesis_hash='6f09966420b2608d1947ccfb0f2a362450d1fc7fd902c29b67c906eaa965a7ae'
block_processing_delay=100
```

**Comment by vinatechpro** [comment]
> Closing this as the solution is in [this](https://github.com/availproject/avail-light/issues/519#issuecomment-2042429179) comment.

I copy your config but it not working. 

```
nano ~/avail-light/config.yml
```
paste your config content.
```
nano /etc/systemd/system/avail-light.service
```
Content avail-light.service
```
[Unit]
Description=Avail Light Client
After=network.target
StartLimitIntervalSec=0
[Service]
User=root
ExecStart= /root/avail-light/target/release/avail-light  --config '/root/avail-light/config.yml' --identity '/root/avail-light/target/release/identity.toml' --network goldberg
Restart=always
RestartSec=120
[Install]
WantedBy=multi-user.target
```

```
systemctl deamond-reload && systemctl start avail-light.service
```

Result:

![image](https://github.com/availproject/avail-light/assets/149946061/3817cc4f-3bea-4032-b7bc-f095fa4d01f7)

**Comment by vinatechpro** [comment]
It's working, isn't it? I'm not sure because there's a change of result which is not success status.
![image](https://github.com/availproject/avail-light/assets/149946061/b74875c9-b360-4c0e-9115-2180319c63f1)

**Comment by vinatechpro** [comment]
> You have passed the seed error stage but from the logs, it seems like your service is still not picking up the config. 
> 
> You can try the following:- 
> 1. Clean up your old `avail_path` artifacts and kill any existing processes using `pkill -9 avail-light`
> 2. Start the client manually from your shell to check for permission issues
>    ` /root/avail-light/target/release/avail-light  --config /root/avail-light/config.yml --identity /root/avail-
>     light/target/release/identity.toml`
> 3. I have a fresh set of RPC endpoints for you to try which you can replace on the `config.yaml` to make sure your client is not running into any connectivity issues.
> `full_node_ws= ["wss://rpc-goldberg.sandbox.avail.tools:443", "wss://lc-rpc-goldberg.avail.tools:443/ws", "wss://avail2.polkadotters.com:443/ws", "wss://avail-goldberg-rpc.polka.p2p.world:443"]`
> 
> The logs for a successful boot sequence will lead to an output like this
> ```
> {"timestamp":"2024-04-09T14:45:21.774967Z","level":"INFO","fields":{"message":"Cells fetched from DHT","block_number":1430,"cells_total":8,"cells_fetched":0,"cells_verified":0,"fetch_elapsed":"984.412µs","proof_verification_elapsed":"1.249µs"},"target":"avail_light::network"}
> {"timestamp":"2024-04-09T14:45:21.906991Z","level":"INFO","fields":{"message":"Cells fetched from RPC","block_number":649370,"cells_total":10,"cells_fetched":10,"cells_verified":10,"fetch_elapsed":"91.597716ms","proof_verification_elapsed":"45.340919ms"},"target":"avail_light::network"}
> {"timestamp":"2024-04-09T14:45:21.907164Z","level":"INFO","fields":{"message":"Confidence factor: 99.90234375","block_number":649370,"confidence":99.90234375},"target":"avail_light::light_client"}
> {"timestamp":"2024-04-09T14:45:21.907276Z","level":"INFO","fields":{"message":"Block available: Dimensions { rows: 4, cols: 256 }","block_number":649370},"target":"avail_light::app_client"}
> {"timestamp":"2024-04-09T14:45:21.908368Z","level":"INFO","fields":{"message":"Message published to clients","topic":"ConfidenceAchieved","published":0,"failed":0},"target":"avail_light::api::v2"}
> {"timestamp":"2024-04-09T14:45:21.908454Z","level":"INFO","fields":{"message":"Maintenance completed","block_number":649370,"map_size":10},"target":"avail_light::maintenance"}
> {"timestamp":"2024-04-09T14:45:21.943147Z","level":"INFO","fields":{"message":"Cell upload success rate for block 649370: 0/10. Duration: 0"},"target":"avail_light::network::p2p::event_loop"}
> ```
> 
> 

Many thanks for your support, I will try it and give feedback.  I have a question, if I clean up the avail-path folder will this affect my reward points calculation?  Because before that I ran early and had many success reports.

**Comment by vinatechpro** [comment]
Admin. I think avail-light has received all of config. But there is still an error message. Is this an error from RPC? I checked the port 7000 response and it still failed to connect.
<img width="1911" alt="image" src="https://github.com/availproject/avail-light/assets/149946061/e9f475a0-2ed6-405f-9f38-db31f5c38d63">

![image](https://github.com/availproject/avail-light/assets/149946061/15d9f32e-3eba-4d69-a10c-962c5ab80f55)

**Comment by vinatechpro** [comment]
unbelievable. `avail-light.service` status had `seed = 'aaa'` but `full_node_ws` still connect to `wss://goldberg.avail.tools:443/ws`. I have no idea, why? 
![image](https://github.com/availproject/avail-light/assets/149946061/2bb1a72d-187e-4d80-ac20-f69e75ce155d)

**Comment by vinatechpro** [comment]
> kad_record_ttl=43200
> ot_collector_endpoint='http://otelcol.lightclient.goldberg.avail.tools:4317'
> genesis_hash='6f09966420b2608d1947ccfb0f2a362450d1fc7fd902c29b67c906eaa965a7ae'
> block_processing_delay=100

It's working successfully. Thank U so much from the bottom of my heart. I have understood all of the matter. 
![image](https://github.com/availproject/avail-light/assets/149946061/183cb2c7-346a-4a6b-90f4-c1d67a828a41)
