### ISSUE TITLE
Docker container with Light Client fails to run on Mac (Apple M1 Pro) 

### ISSUE THREAD

**Issue by vlad2095** [availproject/avail-light#552]
About my system: 
<img width="241" alt="image" src="https://github.com/availproject/avail-light/assets/29329498/604f9f6e-1981-4d5d-9bc2-7b38949ec433">

Issue:
<img width="585" alt="image" src="https://github.com/availproject/avail-light/assets/29329498/c1a48744-deda-49ef-91a7-daddfbf0cbfe">

**Comment by nooga** [comment]
Hey, small update on this, looks like the arm64 `availj/avail-light:v1.8.1` image contains amd64 ubuntu with an arm64 `avail-light` binary and thus the OS cannot load it. 

Running on AppleSillicon:
```
podman run --rm -it --entrypoint=/bin/bash --user=root availj/avail-light:v1.8.1
```

Let's check the binary:
```
avail@3b9823302387:/var/lib/avail-light$ ls -la /usr/local/bin
total 43740
drwxr-xr-x. 1 root  root        25 Apr 26 06:50 .
drwxr-xr-x. 1 root  root        30 Apr 16 02:03 ..
-rwxr-xr-x. 1 avail avail 44787792 Apr 26 06:39 avail-light
avail@3b9823302387:/var/lib/avail-light$ head -n 1 /usr/local/bin/avail-light
ELF���@P^�@8
```

It's there and it is an ELF file. Let's check the size:
```
avail@3b9823302387:/var/lib/avail-light$ stat /usr/local/bin/avail-light
  File: /usr/local/bin/avail-light
  Size: 44787792  	Blocks: 87480      IO Block: 4096   regular file
Device: 51h/81d	Inode: 8709281     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/   avail)   Gid: ( 1000/   avail)
Access: 2024-04-26 06:39:55.000000000 +0000
Modify: 2024-04-26 06:39:55.000000000 +0000
Change: 2024-05-09 12:17:38.803787688 +0000
 Birth: -
```

But it doesn't run:
```
avail@3b9823302387:/var/lib/avail-light$ file /usr/local/bin/avail-light
bash: file: command not found
```

Let's check it with `file`:
```
root@bf28268203f2:/var/lib/avail-light# file /usr/local/bin/avail-light
/usr/local/bin/avail-light: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=6fae12d8b51f8669b648ef35068d453688e65598, for GNU/Linux 3.7.0, with debug_info, not stripped
```

Looks correct! But, let's look around the OS:
```
root@bf28268203f2:/var/lib/avail-light# uname -a
Linux bf28268203f2 6.8.4-200.fc39.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Apr  4 21:00:27 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

It looks like we are on amd64 linux here. Mind you, this is running in Podman machine using applehv which supports rosetta so we can have amd64 linux running. 

Let's check another binary on the system to confirm this:
```
root@bf28268203f2:/var/lib/avail-light# file /bin/ls
/bin/ls: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2f15ad836be3339dec0e2e6a3c637e08e48aacbd, for GNU/Linux 3.2.0, stripped
```

Yep. Your build action is putting aarch64 binary on top of amd64 ubuntu distro image and ships that as `linux/arm64` container image.

**Comment by nooga** [comment]
Thanks for merging @moraesjeremias! Do you have any prediction as to when 1.8.2 will be released?
