### ISSUE TITLE
Include full header in v2/header api

### ISSUE THREAD

**Issue by ecioppettini** [availproject/avail-light#574]
Hello, I noticed that the `v2/header/` endpoint doesn't really show you the actual header. Is there a reason for this? 

In particular, I'm interested in the pre runtime digest, since I'd like to be able to look at the slot number. Would it be feasible to add this? (Or is there another way of getting the slot for a block?). I could just get the full header from de node's rpc, of course, but that involves having access to it besides the light client itself.

**Comment by aterentic-ethernal** [comment]
@ecioppettini , we just didn’t want to commit to the schema without understanding the uses of the light client API. We will add digest to the header and post update here when its done. Thanks for reporting it.

**Comment by cryptosatya** [comment]
Node not running
